### ISSUE TITLE
Genesis 8.1

### ISSUE THREAD

**Issue by AutoDolor** [butaixianran/Blender-Vmd-Retargeting#1]
I have bought your add-on. It works quite well, but it doesn't work in facial and visemes with genesis 8.1 (Yes in body...). Is it my mistake or have you tried it?

**Comment by AutoDolor** [comment]
My bad! The data folder for expressions and control head of 8.1 is in another path....

**Comment by butaixianran** [comment]
Hi, this addon doesn't officially support Genesis 8.1. 

Because G8.1 uses Facial bones for expression, so Daz just doesn't want to offer a lot of facial morphs any more. Most morphs we used for facial expression don't even exist in G8.1. 

But diffeomorphic daz importer brought those morphs back to G8.1. I'm not sure that's officially supported by diffeomorphic's daz importer or just a trick.

So, we do not officially support G8.1, but you can always try it with diffeomorphic's daz importer.
