### ISSUE TITLE
Export....

### ISSUE THREAD

**Issue by AutoDolor** [butaixianran/Blender-Vmd-Retargeting#16]
Hello. Although it works very well in the Diffeomorphic environment, in facial expressions and pseudo-visemes, passed to .duf according to the "action", in posing, save pose, in the body it does not follow the movement and only saves a frame (the initial one. ..) of the whole "dance" of the body. It works worse with the Daz bidge, that if I give the body, (always with reference to the armature of a pmx+vmd), it only moves the hip... I don't know if it's an error in your plugin, or in the export from Diffeo, or from the Daz importer, or from the same pmx structure, which I usually use the same, a Hatsune Miku default for Diva´s project X HD... (It is not a TDA model..., but I get the same results with a TDA as with ones from YYB, even converting the vmd with the "Vmd sizing" program, which I suppose you know...). The camera works almost perfectly in all cases. If I do a bake action (either in model or pose mode...in Blender), exported as fbx, the same result...

**Comment by butaixianran** [comment]
imported vmd motion is on multiple NLA tracks. That's not a part of Diffeomorphic daz import addon. If you want to save it, you need to learn how to use NLA of blender.

For example, you need to know how to bake multiple NLA tracks' motion into one.

Camera motion is ok for you, because vmd's camera motion has no layers, so there is no multiple tracks.

**Comment by butaixianran** [comment]
No reply
